name: Codecov

# Triggers the workflow on pull request events.
on: pull_request

jobs:
  JavaCheckStyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        entrypoint: bash
        args: ['bash <(mvn clean test)']
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          file:
