on: ["push", "pull_request"]


name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Run tests
      run: |
        mvn clean test

        - name: Upload coverage report

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
