name: Java Style Check

# Triggers the workflow on pull request events.
on: pull_request

jobs:
  JavaCheckStyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style against Google Java style guide
        uses: codecov/codecov-action@master
